name: build-efi

on:
  workflow_dispatch:
    inputs:
      department:
        description: "Department"
        required: true
      machine:
        description: "Machine"
        required: true
      kernel_url:
        description: "Custom kernel URL (optional)"
        required: false
      ubuntu_iso_url:
        description: "Custom Ubuntu ISO URL (optional)"
        required: false
      autoinstall_url:
        description: "Custom autoinstall URL (optional)"
        required: false

env:
  DEPARTMENT: ${{ github.event.inputs.department }}
  MACHINE: ${{ github.event.inputs.machine }}
  KERNEL_URL: ${{ github.event.inputs.kernel_url }}
  UBUNTU_ISO_URL: ${{ github.event.inputs.ubuntu_iso_url }}
  AUTOINSTALL_URL: ${{ github.event.inputs.autoinstall_url }}

jobs:
  build:
    name: Build EFI Bootloader
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.ref_name }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v4

    - name: Show configuration inputs
      run: |
        echo "DEPARTMENT=${DEPARTMENT}"
        echo "MACHINE=${MACHINE}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build EFI
      run: |
        echo "Building EFI"
        NEW_NAME=$(./script/build_release | grep "NEW_NAME=" | cut -d'=' -f2)
        echo "NEW_NAME=$NEW_NAME" >> $GITHUB_ENV

    - name: Upload EFI
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.NEW_NAME }}
        path: buildout/ipxe/${{ env.NEW_NAME }}
        retention-days: 90

