name: local_dev

on:
  push:
    branches: [feat-efi-pipeline]

env:
  EFI_FILENAME_PREFIX: "netboot.xyz-rampart-aios"
  ARTIFACT_RETENTION_DAYS: 90

jobs:
  build-release:
    name: Build and Release for local_dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run local_dev release workflow
      id: build_local_dev
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        source ./script/workflow.sh
        output=$(run_build_local_dev local_dev)
        echo "$output"
        echo "version=$(echo "$output" | grep "version=" | tail -1 | cut -d'=' -f2)" >> $GITHUB_OUTPUT
    - name: Upload EFI file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: netboot.xyz-rampart-aios-${{ steps.build_local_dev.outputs.version }}.efi
        path: buildout/ipxe/netboot.xyz-rampart-aios-${{ steps.build_local_dev.outputs.version }}.efi
        retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }} 