name: local_dev

on:
  workflow_run:
    workflows: ["pull-requests"]
    types: [completed]
    branches:
      - local_dev
      - feat-efi-localdev-pipeline
  workflow_dispatch:

jobs:
  dev-build:
    name: Build Development Release
    runs-on: ubuntu-latest
    concurrency:
      group: dev-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v4
      with:
        ref: local_dev

    - name: Download EFI artifacts from PR workflow
      uses: actions/download-artifact@v4
      with:
        name: ${{ github.event.workflow_run.outputs.efi-file-name }}
        path: buildout/ipxe/

    - name: Set Development Release Tag
      run: echo "release_tag=v0.0.1-dev" >> $GITHUB_ENV

    - name: Tag dev Release
      run: |
        ./script/tag ${{ env.release_tag }}

    - name: Extract release notes
      id: extract-release-notes
      uses: ffurrer2/extract-release-notes@v2

    - name: Create dev Release and Upload Assets
      uses: svenstaro/upload-release-action@v2
      with:
        file: buildout/ipxe/*
        file_glob: true
        overwrite: true
        prerelease: true
        release_name: ${{ env.release_tag }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.release_tag }}
        body: ${{ steps.extract-release-notes.outputs.release_notes }}